### ISSUE TITLE
Error while importing the library

### ISSUE THREAD

**Issue by owen2345** [vocaroo/simple-audio-recorder#1]
I can not import the package

```
import { AudioRecorder } from "simple-audio-recorder/react";
```
Raises the following error: The package target "dist/react.js" is invalid

Thanks

**Comment by bobbles911** [comment]
Hi. The basic AudioRecorder should be imported like:

`
import AudioRecorder from "simple-audio-recorder";
`

Only the React parts come from "simple-audio-recorder/react".

If that doesn't help please create a minimal example.
